channels:
  - pyg
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda=11.8 
  - pyg
  - networkx=3.1
  - numpy
  - scipy
  - wand
  - matplotlib
  - seaborn
  - pandas
  - jupyterlab 

  
